### ISSUE TITLE
ParallaxBanner minimum height

### ISSUE THREAD

**Issue by josefleventon** [jscottsmith/react-scroll-parallax#101]
## Giving ParallaxBanner a minimum height

* I'd like to be able to keep the ParallaxBanner at a certain minimum height when scrolling.
* Example: My banner is 65vh high, and the more I scroll the more it retracts up. I'd like it to stop at say 30vh and become fixed, keeping the image up there but having the content below scrollable.

Is there any way I could implement this?

**Comment by jscottsmith** [comment]
Sorry, not with this package, no. This package was meant for applying effects to elements that stay in the document flow. 

It sounds like you want to transition an element from relative to fixed/sticky while changing the height of the banner. You may need to implement something custom for that because I don't know any out of the box solutions.
