### ISSUE TITLE
ParallaxBanner > When scroll position at top, transform doesn't start from 0 

### ISSUE THREAD

**Issue by bastienlm** [jscottsmith/react-scroll-parallax#122]
## Trouble With Implementation

Describe the trouble you are having considering the following:

Hello,
First, thanks for your work.

I've the same issue explained here https://github.com/jscottsmith/react-scroll-parallax/issues/59 but with the `<ParallaxBanner />` component.

![image](https://user-images.githubusercontent.com/13004368/142173459-ad96dac1-6414-48c8-9e81-aae7a004e93e.png)

how you can see, I'm on the top of the page and the transform start at `8.06624%`

This is my code:
```
<ParallaxBanner
                  className="hero__image"
                  layers={[
                    {
                      image:
                        homePageMainMedia.url +
                        "?format=hero&width=1500&height=624&size=1&cover=true",
                      amount: 0.5,
                      props: {
                        style: {
                          backgroundSize: "auto",
                          backgroundRepeat: "no-repeat",
                        },
                      },
                    },
                  ]}
                  style={{
                    height: "625px",
                  }}
                >
                  <div className="hero__image__loader"></div>
                </ParallaxBanner>
```

(If I set amount to 0, the initial position it's OK, but the parallax doesn't work)

**Comment by jscottsmith** [comment]
@bastienlm Ya this is by design. I understand why it may seem like it should start at zero, but let me try and explain why this behaves this way.

Consider when the transforms start or the beginning, which is when the top of the element enters the bottom of the view. Then consider the end which is when the bottom of the element leaves the top of the view.

Now in your case, I'm guessing this banner is at the top of the page (top of the element is at the top of the view), and which means the parallax element is _about_ half way though it's total transition.

Also to obfuscate this more, the `amount` value is both the start and end values for `y` transforms in `<ParallaxBanner>` which is why the position is ok if it's set to `0`. You can't set them independently in this component. You could create your own which allows for more independent control of the start/end values since this component is just a wrapper of the main `<Parallax>` component. See the source: https://github.com/jscottsmith/react-scroll-parallax/blob/develop/src/components/ParallaxBanner.js#L68

Anyway, sorry for the confusion. I need to do a better job illustrating how this lib applies transformation.

**Comment by kzt22** [comment]
Is there a way to get the initial transform value set from the Parallax?
