### ISSUE TITLE
Can set transition of the component depend on the progress in horizontally scroll?

### ISSUE THREAD

**Issue by ngocducdim** [jscottsmith/react-scroll-parallax#131]
- Hi I have question, when scrolling horizontally we will have the progress value right? So let said at the progress value 0.1 the `<Parallax />` component will have property `translateX={1}` and at the progress value 0.5 the `<Parallax />` component will have property `translateX={5}`, can we do that? I want implement the animation like below: 
![ezgif-5-4fb0fe82fb](https://user-images.githubusercontent.com/97713182/152506018-a9b1586f-6cab-4530-9b83-ac0cd4f238d1.gif)

**Comment by jscottsmith** [comment]
@ngocducdim based on the visual, it may be possible. Not quite how you describe -- you must provide start end values for `translateX` like `translateX={['-100%, '0%']}` that will correspond to the progress `0 - 1`. Since these elements are fixed in view and don't naturally scroll you would have to use `startScroll` and `endScroll` [config values](https://react-scroll-parallax.damnthat.tv/docs/usage/parallax-props#configuration-props) to determine the progress. I can try and mock something up for you.

**Comment by jscottsmith** [comment]
@ngocducdim I put together a [CodeSandbox](https://codesandbox.io/s/react-scroll-parallax-fixed-horizontal-scroll-bm4rx)

This is probably the closest you can get. The main limitation I see is that there's no ability to set key points along the animation -- only a start and end value. If that works for you then you'll be ok, but if you need more advanced timeline/keyframes then I'd suggest looking at a different library such as GSAP ScrollTrigger.

Let me know if this helps.

**Comment by ngocducdim** [comment]
Hi sorry for late reply, your demo is nice really helpful for the basic one, I will take a look the GSAP ScrollTrigger, thank you
