### ISSUE TITLE
parallax scroll speed option

### ISSUE THREAD

**Issue by ChCosmin** [jscottsmith/react-scroll-parallax#14]
Would be nice if there was a scroll speed variable where we could set how fast the parallax-scroll would happen, also maybe some better explanation of what each attribute representes and how it affects the parallax effect

**Comment by jscottsmith** [comment]
@ChCosmin Which props are you having trouble understanding? Maybe a better demo allowing to change all the props and see the effects would help? There's this [demo](https://jscottsmith.github.io/react-scroll-parallax-examples/examples/parallax-test/) of course which hopefully you've looked at, but it could be improved.

**Comment by ChCosmin** [comment]
I had trouble understanding how the offsetYMin, offsetYMax worked, i tried a lot of combinations and variables in them but i couldn't make it look or behave like i wished (not sure if the structure of my html was a problem or not) but yeah. as well as the slowerscroll prop DID make it slower but not as slow as i needed so having the ability to put a speed variable on it would've helped, unless you can influence the speed/ammount of parallaxing the elemnt does with a good combination of offsets but i didn't manage to understand that

**Comment by jscottsmith** [comment]
@ChCosmin well if you are still having trouble I can take a look at your code. Sounds like it may be an issue with the setup. Basically the larger the offsets, the more pronounced the effect. The `slowerScrollRate` prop effectively just flips these offsets internally so that it will appear that the element it moving slower than the default rate of scroll. 

As for a scroll rate/speed prop, I'm not so sure. It's a nice idea but doesn't fit so well with how this package was built.

Going to close this but if you need some help just send me a repo or code example and I'll have a look.
