### ISSUE TITLE
Incorrect initial loading of values

### ISSUE THREAD

**Issue by cireix** [jscottsmith/react-scroll-parallax#142]
Initial values should be the same as what is inputted. 

VSCode:
![image](https://user-images.githubusercontent.com/30269755/158049791-6f0c117c-0873-498b-93a1-ffb52cba8a1f.png)

Rendered:
![image](https://user-images.githubusercontent.com/30269755/158049824-c067a8cf-26bd-4f86-bcf6-6e0849068cc5.png)

The rendered translateY value should be the same as the start value of translateY in the code.

**Comment by jscottsmith** [comment]
Are you able to provide a link to your site or a demo of the behavior? It would be helpful in determining the cause of this behavior.

This may be due to the way translate effects are scaled in certain cases. You can disable this behavior with the option `shouldDisableScalingTranslations`, see the [config prop options](https://react-scroll-parallax.damnthat.tv/docs/usage/parallax-props#configuration-props).

**Comment by jscottsmith** [comment]
Not sure how to reproduce this -- here's [my attempt](https://codesandbox.io/s/react-scroll-parallax-bug-tqe3pw?file=/src/App.tsx) based on the setup you have, but everything looks normal to me.

**Comment by cireix** [comment]
Here's a [playground](https://codesandbox.io/s/nervous-water-4v7nfw) to work with.

**Comment by jscottsmith** [comment]
Thanks! that helps. I see the issue now and have an idea of what may be causing it. I will look into it and see if I can get a fix out soon.

**Comment by jscottsmith** [comment]
Published a fix in the dependency. You should be able to see the fix in `v3.0.5`. Example: https://nujwyi.csb.app/

Let me know if you have any trouble.

**Comment by cireix** [comment]
Thanks for the quick fix!
