### ISSUE TITLE
Can't get an <a> tag to be clickable inside a layer

### ISSUE THREAD

**Issue by jacobsilver2** [jscottsmith/react-scroll-parallax#201]
Hi,
I'm trying to get some text on a banner layer to be a link, and not having much luck. I've actually managed to reproduce this on the Advanced Banner example, and have provided a fork here:

https://codesandbox.io/embed/react-scroll-parallax-hero-banner-forked-gcjjhc?fontsize=14&hidenavigation=1&theme=dark

The only code I've changed so far is:
```
        <a href="https://www.facebook.com">
          <h1 className="headline white">Hello World!</h1>
        </a>
```

I thought maybe it was a z-index thing? But that didn't seem to work. Thanks in advance for the help.

**Comment by jscottsmith** [comment]
@jacobsilver2 this is because there are multiple layers on top of the layer with a link. You could use `z-index` to bring the link to the top, but that would break the design.

Instead, disable pointer events with [`pointer-events: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) on all the layer on top of the link.

Here's the updated Codesandbox:

https://codesandbox.io/embed/react-scroll-parallax-hero-banner-forked-gcjjhc?fontsize=14&hidenavigation=1&theme=dark
