### ISSUE TITLE
Styles not defined in documentation 

### ISSUE THREAD

**Issue by drb1** [jscottsmith/react-scroll-parallax#214]
Please add styles files too of related effects.I cannot find any styles of given example in documentation

**Comment by jscottsmith** [comment]
Can you elaborate? Which example are you referring to? I'm open to making improvements to the documentation but I'll need more info to act on. 

Most of the styles are there in some capacity they just may not be written in the docs explicitly. This is because this library doesn't have much of an opinion on how you add styles to an element. If you need to see the styles of a specific example take a look at the source code and you will find Tailwind styles or CSS modules. You can also use the browser inspector to see the applied styles.
