### ISSUE TITLE
onLoad function does not fire on image layers

### ISSUE THREAD

**Issue by lexwebb** [jscottsmith/react-scroll-parallax#231]
## Bug

I'm attempting to create a loading animation for when my images have downloaded to the client. I'm doing this to nicely transition from the low res fallback image to the high res images i'm using for parallax. 

Unfortunately the onLoad function that seems to exist in the types for a layer does not ever seem to get called, which means my images never get style updates onLoad.

Here's a codesandbox demonstrating https://codesandbox.io/s/react-scroll-parallax-template-forked-3x9x83?file=/src/App.tsx

**Comment by jscottsmith** [comment]
@lexwebb Thanks for the Codesandbox.

The reason your `onLoad` event isn't firing is because the `layers` in ParallaxBanner use a div with a background image set to cover.

<img width="755" alt="Screenshot 2023-11-04 at 10 14 27 PM" src="https://github.com/jscottsmith/react-scroll-parallax/assets/7143485/cbd26481-11c3-4b0d-a66d-6f365573b97a">

If need an `img` element with a load event handler you can see how to set that up in [the documentation](https://react-scroll-parallax.damnthat.tv/docs/usage/components/parallax-banner-component#example-using-parallaxbannerlayer) 

Keep in mind you will also need to style the image to work for you're use case, probably with `object-fit: cover`. Hope that helps.
