### ISSUE TITLE
Can you do parallax and the image will remain fixed postion?

### ISSUE THREAD

**Issue by OptimaLPro** [jscottsmith/react-scroll-parallax#253]
Hey there,

I want to know if i can achieve

https://github.com/jscottsmith/react-scroll-parallax/assets/65537815/bc510fa3-75b6-46eb-80e5-d26ef14b94aa

 this effect of parallax - that you are scrolling down and the image is remain "fixed" with slightly parallax effect.

website: https://www.azurim.com/

**Comment by jscottsmith** [comment]
@OptimaLPro 

Yes you can. Because the image is fixed you need to setup parallax using a [targetElement](https://react-scroll-parallax.damnthat.tv/docs/usage/parallax-props#configuration-props) which will determine the progress.

Here's a [Codesandbox](https://codesandbox.io/p/sandbox/react-scroll-parallax-fixed-position-image-using-target-element-6cj6fw?file=%2Fsrc%2FApp.tsx%3A7%2C49) that demonstrates a similar effect as the site you shared.
