### ISSUE TITLE
One chrome-mobile, a jump after address bar scroll

### ISSUE THREAD

**Issue by grod220** [jscottsmith/react-scroll-parallax#27]
BUG report:

On chrome for mobile (Android), whenever you scroll past the address bar at the top, there is a small stutter in the parallax image. It seems to resize to accommodate more space that's available. 

Evident on personal dev project and examples: https://jscottsmith.github.io/react-scroll-parallax-examples/examples/parallax-example/.

**Comment by jscottsmith** [comment]
Thanks for the report but this is just do to styling, not the parallax library. Guessing I used 100vh to position the section and Chrome resizes the window when the bar goes away. This is a pretty common issue when dealing with full screen positioning of elements. 

Going to close since it doesn't relate to the lib and I don't plan on fixing the example.

**Comment by grod220** [comment]
Chrome does not resize the view height when the bar goes away as of last year (see: https://developers.google.com/web/updates/2016/12/url-bar-resizing). Think it may be something else as I've seen it on a number of other examples. I also noticed that the background jump is slightly less pronounced when using Parallax Banner.

**Comment by jscottsmith** [comment]
Interesting, thanks for sharing. I hadn't realized they had updated that behavior.

> Think it may be something else as I've seen it on a number of other examples.

If you have an idea of what's causing this related to the lib, I'm open to hearing about it.

Also, I should say, I don't recommend using parallax effects on mobile devices. I should probably make that more clear in the readme (it's all the way at the bottom in the PSA) ;)
