### ISSUE TITLE
support: how to access parallax-inner by its ref

### ISSUE THREAD

**Issue by zilahir** [jscottsmith/react-scroll-parallax#29]
Hey! 

I want to access the dom element parallax-inner by its ref.

I wanna do something like the following: 

```
componentDidMount() {
        const aboutParallax = this.secondParallax;
        let aboutParallaxTransform = window.getComputedStyle(secondParallax, null).transform;
        console.log(aboutParallaxTransform);
      });
    }

<Parallax offsetXMax={-20} offsetXMin={20} slowerScrollRate  ref={(parallax) => { this.secondParallax = parallax; }}>
 ...
 </Parallax>


/* ERROR: 

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at HTMLDocument

*/
```

Any help would be appreciated! Thank you!

**Comment by zilahir** [comment]
Additional info: i want to get the `transform: translae3d` property, when `scroll` event is detected.

**Comment by jscottsmith** [comment]
Hmm, why do you need to do that? Seems strange to me. 

Based on your code, `this.secondeParallax` is referencing a class, not an element. That's why you are getting the error. You could get the inner ref from that class. It should be the `_inner` property, [see here](https://github.com/jscottsmith/react-scroll-parallax/blob/master/src/components/Parallax.js#L110).

**Comment by zilahir** [comment]
Thanks! 

Could you provide a quick example how can i access that ref from my Comonent? 

The component where `Parallax` is also placed. That would be a great help!

Thanks!

**Comment by jscottsmith** [comment]
```
this.secondeParallax._inner
```

That should work based on your code.

Though, I wouldn't recommend it. Those refs are meant to be private and accessing DOM properties from them is poor practice.
