### ISSUE TITLE
Only work properly when I resize my browser manually

### ISSUE THREAD

**Issue by peterEycyeh** [jscottsmith/react-scroll-parallax#58]
Hi, I really like this repo. It is amazing, especially in version 2. quite clean and easy to implement. However, the parallax always work properly when I resize my browser manually. Thus, I think it is because of the cache, but I update updating the cache when image load, it seems nothing happened. Even I set a timer say update the cache after 5 second. Would you please give me a hint to let me know if there is anything that might cause the issue? Thank you so much!

**Comment by peterEycyeh** [comment]
Because I have a video(around 10 second) on initial load. I am not sure if that affect. And Is it possible to set a timeout to force it update(re-calculate) after video end. Thank you!

**Comment by jscottsmith** [comment]
@peterEycyeh definitely cache related. Can you share a repo or live site with me, then I can probably help out.

**Comment by jscottsmith** [comment]
Try updating cache after the video meta data loads. [See here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadedmetadata_event)

The height/width should be know at that point, and cache will need to be updated with those values.

Alternatively, set a width/height on the video or container, so that the parallaxed element isn't dependent on loading assets.
