### ISSUE TITLE
When scroll position at top, transform doesn't start from 0

### ISSUE THREAD

**Issue by kimmobrunfeldt** [jscottsmith/react-scroll-parallax#59]
## Expected Behavior

When setting 

```js
<Parallax y={['0px', '200px']}>
  <img src={myIcon} />
</Parallax>
```
and reloading page (scroll position is at the top), I would expect to `.parallax-inner` transform to start from 0px Y-axis transform, like this: `transform: translate3d(0%, 0px, 0px);`

## Actual Behavior

`.parallax-inner` class starts with `transform: translate3d(0%, 112.586px, 0px);`, and the 112.586px isn't the height or width of the icon being transformed. I'm not sure where this number is coming from.

Our existing CSS positions the icon in the correct place, but now we would need to compensate the initial 112.586px, and I'm not sure if that number is stabile.

## Steps to Reproduce the Problem

Mentioned above.

## Environment

* Version: 2.1.1
* Platform: MacOS 10.14.3
* Browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by jscottsmith** [comment]
@kimmobrunfeldt is this element within the viewport when scroll is at the top? Is there a repo or live link I can look at?

**Comment by kimmobrunfeldt** [comment]
The element is in viewport when the page is scrolled to top. I'll try to make this a reproducible example and send the link! Currently it happens in the context of our website but I'll separate it out.

**Comment by kimmobrunfeldt** [comment]
I setup an example here: https://github.com/kimmobrunfeldt/react-scroll-parallax-example, which is live at https://affectionate-lalande-e5a343.netlify.com/

What I expect: (without Parallax added)

![Screenshot 2019-04-12 13 25 30](https://user-images.githubusercontent.com/1232405/56030874-9fa45c00-5d26-11e9-84a2-0698e77f6d65.png)


Relevants part of example code here:

* Parallax: https://github.com/kimmobrunfeldt/react-scroll-parallax-example/blob/master/src/App.js#L11
* ParallaxProvider: https://github.com/kimmobrunfeldt/react-scroll-parallax-example/blob/master/src/index.js#L5


What happens (with Parallax added, this is the current state of the example):

![Screenshot 2019-04-12 13 25 42](https://user-images.githubusercontent.com/1232405/56030883-a4691000-5d26-11e9-80ef-2d3ecd13bd5a.png)

**Comment by jscottsmith** [comment]
Ok, this is expected.

The offsets are applied based on the position in the viewport, which is determined by the top of the element at the bottom of the view as `0%` (0px of `y=[0px, 100px]`) to the bottom of the element at the top of the view which is `100%` (100px of `y=[0px, 100px]`).

If the element is centered in the view naturally (without parallax offsets), it's 50% through its transition in the viewport and the parallax offsets you defined (0px - 100px) mean it would be about 50px from its natural position.

If you want it centered initially try `y=[-50px, 50px]`.

Hope this helps. Let me know if you have more questions.

**Comment by jack-arms** [comment]
I'm curious about this as well -- I think I understand how the element with parallax is in the middle of the page, where you can scroll above and below it, but I'm interested in the use case where an element is near the top of the page, starting with its normal display, and then the parallax effect only happens when you scroll down past it.

For example, see https://codesandbox.io/s/interesting-knuth-2r46w?fontsize=14 for a basic demo. I want the "Welcome!" header to be displayed without any transforms when you're at the top of the page, and for the letters to expand as you scroll down.

If setting `0` for the min offset doesn't work because it's already near the top of the viewport, then it seems like setting a negative min offset is necessary in order to have no parallax initially, but in this case how can I calculate what this negative value should be?
