### ISSUE TITLE
Using react-scroll-parallax with GatsbyJS

### ISSUE THREAD

**Issue by OPerel** [jscottsmith/react-scroll-parallax#65]
Hello and thanks for the package!

I'm trying to use the package in a Gtasby blog (v 2.1.2).
[here is the repo](https://github.com/OPerel/G-blog).
It's not working when I try using `<ParralaxProvider>` in a layout component shared across multiple pages. I undrestand that the parallax element's position is calculated based on the scrolling position on the entry page, so it breaks when navigating between pages.
Any chance there's a simple workaround you know of? Maybe it can be added as a feature? Or it can't be solved easily?  

Thanks a lot!

**Comment by jscottsmith** [comment]
Happy to help @OPerel 

But I pulled the repo and it seems to be working fine as is. Looks like you have the provider in the `layout.js` and when navigating between pages the parallax components still work. 

Maybe I'm missing something?

**Comment by OPerel** [comment]
Hey,

Thanks for the quick response.
Try scrolling to the middle of the homepage, navigate to the about page, and scroll down to see the footer.
That's the only parallax element shared between the two pages.

**Comment by jscottsmith** [comment]
Ok I understand now.

Two things you can do:

1. Update the controller when the page location changes. This will require creating a component that accesses the controller. Here's a quick sample that will update each time a `location` prop changes:
```js
import { withController } from "react-scroll-parallax"

class Footer extends Component {
  static propTypes = {
    parallaxController: PropTypes.object,
  }

  componentDidUpdate(prevProps) {
    if (prevProps.location !== this.props.location) {
      this.props.parallaxController.update()
    }
  }

  render() {
    return (
      <footer>
        <Parallax y={["30px", "-100px"]}>
          <p>My G-Blog</p>
        </Parallax>
        <Parallax y={["30px", "-100px"]}>
          <p>
            © {new Date().getFullYear()}, Built with{" "}
            <a href="https://www.gatsbyjs.org">Gatsby</a>
          </p>
        </Parallax>
      </footer>
    )
  }
}

export default withController(Footer)
```

2. Move the footer to a page level component so that it is unmounted/mounted with each route change.

Either should work. Let me know if you still have trouble.

**Comment by OPerel** [comment]
So I'm trying to go with your first suggestion because the second one messes up some other layouts I'm trying to achieve.
The thing is it's not working.
`prevProps` and `this.props` don't have a location property. 
So I tried passing a location prop manually to the footer from the layout component.
But then `prevProps.location` and `this.props.location` are equal.
Also, my knowledge of react lifecycle methods is limited, but from logging to console from inside `componentDidUpdate()` I see it's not being called on navigating between page.
The repo is updated with these changes.
Thanks!

**Comment by jscottsmith** [comment]
@OPerel Sorry should've clarified where the `location` prop will come from.

Gatsby passes a `location` object to `layout.js` -> https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#4-pass-history-location-and-match-props-to-layout

Take this prop and pass it the the `<Footer location={location}>` so that each time it changes the footer will update.

**Comment by OPerel** [comment]
Hey, 
Thanks I'm getting the location object now.
The thing is `componentDidUpdate()` isn't called on page navigation.
I know of `onRouteUpdate()` from gatsby's browser api, but I can't figure how to use it for updating `parallaxController`.  
 
Sorry, i'm kinda new to all this...

**Comment by jscottsmith** [comment]
@Operel ya you're right, I'm not too familiar with Gatsby and why this may be the case.  I'll try and dig into this a bit more and figure out a solution. Meanwhile you may also want to try moving the `ParallaxProvider` from `layout.js` to within this Gatsby API -> https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement.

**Comment by OPerel** [comment]
I moved `ParallaxProvider` to `wrapRootElement` in gatsby-browser.js. 
Result is the same...
I'll be waiting for a solution.
Thanks a lot!

**Comment by jscottsmith** [comment]
@OPerel So the problem stems from Gatsby reseting scroll position to the top when navigating pages. This is a good behavior to have in an app, but the problem is I don't know when this hook run in Gatsby. To fix the parallax controller must be updated *after* this scroll hook. You can see this when logging out the scroll position on mount:

```js
class Footer extends Component {
  componentDidMount() {
    // update the controller cache with incorrect scroll value
    console.log("componentDidMount", window.pageYOffset)
    this.props.parallaxController.update()

    // set timeout to update the controller after window scroll is reset
    setTimeout(() => {
      this.props.parallaxController.update()
      console.log("cdm timeout", window.pageYOffset)
    }, 500)
  }

  render() {
    return (
      <footer>
        <Parallax y={["0px", "-300px"]}>
          <p>My G-Blog</p>
        </Parallax>
        <Parallax y={["0px", "-300px"]}>
          <p>
            © {new Date().getFullYear()}, Built with{" "}
            <a href="https://www.gatsbyjs.org">Gatsby</a>
          </p>
        </Parallax>
      </footer>
    )
  }
}
```

will result in something like this:
 
```
componentDidMount 324
cdm timeout 0
```

So, not sure how to fix this problem for you. A `setTimout` is a hacky fix at best. If you can disable Gatsby's scroll management and implement your own that would be a start. Or if there's an api to know *when* this scroll is reset that would also help. Googling around hasn't provided me much answers, maybe theres something in here that's useful: https://github.com/gatsbyjs/gatsby/issues/7454. 

Other than that I don't have further suggestions.

**Comment by jscottsmith** [comment]
Opening this back up in case someone knows more about Gatsby and has an answer.

**Comment by OPerel** [comment]
@jscottsmith I'll try looking into it sometime.
In the meanwhile I limited all parallax elements use to the homepage and used pure CSS to create some effects on other pages.   

Thanks a lot for all your help!

**Comment by benmacdonald** [comment]
@OPerel I'm using this in my gatsby project. I add the provider in the `gatsby-browser.js` file.
It uses the wrapRootElement API to wrap the root element with the ParallexProvider.

For example, my `gatsby-browser.js` looks like this:
`/**
 * Implement Gatsby's Browser APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/browser-apis/
 */
import React from "react"
import { ParallaxProvider } from 'react-scroll-parallax';
export const wrapRootElement = ({ element }) => (
  <ParallaxProvider>{element}</ParallaxProvider>
)`

Once you do this you can use the `<Parallax />` component in your project as described in the README.

**Comment by Kevinnko** [comment]
@OPerel @jscottsmith  Hey guys, I would like to revive this issue. I have a parallax element on index page that works great, but once I navigate to another page, scroll down, and click on link to go back to index, the parallax element offset is based on the previous page scroll. I tried different things, including creating a custom Link component like [in this issue ](https://github.com/gatsbyjs/gatsby/issues/7454#issuecomment-415786239), and the [ParallaxCache custom hook](https://github.com/jscottsmith/react-scroll-parallax#example-usage-of-context) as explain in Readme. But none of these worked for me. @OPerel did you figured it out ?

**Comment by OPerel** [comment]
Hey @Kevinnko,
I didn't really solve anything. As mentioned in my last comment I limited the use react-scroll-parallax library to the homepage or index, and used CSS to supplement it on other pages. 
You can check out the result [here](https://gatsby-parallax-blog.netlify.com/). There you'll also find a link to the source code.
Good luck!

**Comment by jscottsmith** [comment]
@Kevinnko @OPerel Out of curiosity I tried troubleshooting this issue again in a new Gatsby starter and I've been unable to reproduce it. Which is weird because I did see this issue in @OPerel's repo before.

Notably I'm using the latest Gatsby starter and applying the `ParallaxProvider` via the Gatsby `wrapPageElement` api. 

You can see how I've integrated the parallax here. [Pull the repo](https://github.com/jscottsmith/gatsby-parallax-test) and scroll/navigate between pages -- should maintain consistent parallax.

https://github.com/jscottsmith/gatsby-parallax-test/commit/8fb8ef8cdadda619275672d9ba9f0439dd77f0e2

@Kevinnko are you using the `wrapPageElement` api? Can I take a look at your repo?

**Comment by Kevinnko** [comment]
Hi @jscottsmith Unfortunately I can't show you the repo. I didn't use the wrapPageElement api, but I just tried and it seems to be working, together with the ParallaxCache component. Also, thank you for your test repo. I cloned it and I think you have the same problem as I described, here is a little screenshot of what's happening : 

![react-scroll-parallax](https://user-images.githubusercontent.com/45763760/68121889-3e81e700-ff09-11e9-9906-9d9e19d1ce78.gif)

When scrolling down on page 2, and going back to page 1, the scroll position stays the same as in page 2, and the image is not well positioned, with the purple background on top of it, instead of bottom.

Also I would like to share with you a weird thing in the ParallaxCache component. Here is the code 

```import { useLayoutEffect } from 'react';
import { useController } from 'react-scroll-parallax';
import window from 'global/window';

const ParallaxCache = () => {
  const { parallaxController } = useController();

  useLayoutEffect(() => {
    const handler = () => {
      setTimeout(() => {
        parallaxController.update();
      }, 300);
    };
    handler();
    return () => {
      // this console.log makes a difference :
      console.log(window.pageYOffset);
    };
  }, [parallaxController]);

  return null;
};

export default ParallaxCache;
```
When I take off the console.log in the returned function in the hook, the image jumps :s I've never seen a console.log changing the outcome...

**Comment by fncombo** [comment]
> @Kevinnko @OPerel Out of curiosity I tried troubleshooting this issue again in a new Gatsby starter and I've been unable to reproduce it. Which is weird because I did see this issue in @OPerel's repo before.
> 
> Notably I'm using the latest Gatsby starter and applying the `ParallaxProvider` via the Gatsby `wrapPageElement` api.
> 
> You can see how I've integrated the parallax here. [Pull the repo](https://github.com/jscottsmith/gatsby-parallax-test) and scroll/navigate between pages -- should maintain consistent parallax.
> 
> [jscottsmith/gatsby-parallax-test@8fb8ef8](https://github.com/jscottsmith/gatsby-parallax-test/commit/8fb8ef8cdadda619275672d9ba9f0439dd77f0e2)
> 
> @Kevinnko are you using the `wrapPageElement` api? Can I take a look at your repo?

Hi @jscottsmith

I noticed that the issue happens when the pages you navigate between are different heights. For example, set index to `300vh` and page 2 to `100vh` - now when you navigate from index to page 2 the parallax on it will break.

I have tried using `useEffect` to call `parallaxController.update()` but that doesn't fix it.

Another strange thing is if you start on index and navigate to page 2, the parallax on page 2 will break, but will still be okay when you navigate back to index using a link. However, if you start on 2 page and navigate to index, the parallax there will not be broken even though it wasn't your entry page. But even in this case, going to page 2 will break the parallax there again.

I also suspected that it might be due to Gatsby "pre-rendering" pages of links when they are in view, but that doesn't seem to be the cause of the problem either because programmatically going to page 2 using `navigate('/page-2/')` does not make a difference from using `<Link>`.

Hope this helps.

**Comment by davwheat** [comment]
@fncombo 

YOU. UTTER. GOD.

I love you for this workaround! I've spent the best part of a few hours working out whats wrong!

**Comment by ajsmth** [comment]
> Hi @jscottsmith Unfortunately I can't show you the repo. I didn't use the wrapPageElement api, but I just tried and it seems to be working, together with the ParallaxCache component. Also, thank you for your test repo. I cloned it and I think you have the same problem as I described, here is a little screenshot of what's happening :
> 
> ![react-scroll-parallax](https://user-images.githubusercontent.com/45763760/68121889-3e81e700-ff09-11e9-9906-9d9e19d1ce78.gif)
> 
> When scrolling down on page 2, and going back to page 1, the scroll position stays the same as in page 2, and the image is not well positioned, with the purple background on top of it, instead of bottom.
> 
> Also I would like to share with you a weird thing in the ParallaxCache component. Here is the code
> 
> ```
> import { useController } from 'react-scroll-parallax';
> import window from 'global/window';
> 
> const ParallaxCache = () => {
>   const { parallaxController } = useController();
> 
>   useLayoutEffect(() => {
>     const handler = () => {
>       setTimeout(() => {
>         parallaxController.update();
>       }, 300);
>     };
>     handler();
>     return () => {
>       // this console.log makes a difference :
>       console.log(window.pageYOffset);
>     };
>   }, [parallaxController]);
> 
>   return null;
> };
> 
> export default ParallaxCache;
> ```
> 
> When I take off the console.log in the returned function in the hook, the image jumps :s I've never seen a console.log changing the outcome...
> 
> UPDATE : On build time, the cache component throws an error due to the useController hook and the parallaxController being falsy. Is there any workaround for that problem ?


The issue is from these lines here:

https://github.com/jscottsmith/react-scroll-parallax/blob/f9f84fc41e436c24774503c6242df66f614ea224/src/components/ParallaxProvider.js#L8-L17

https://github.com/jscottsmith/react-scroll-parallax/blob/f9f84fc41e436c24774503c6242df66f614ea224/src/components/useController.js#L7-L11

You can work around this by accessing the exported context directly, just make sure you verify the controller is defined. In your case you're using layout effect, I'm not sure the implications for SSR but you might have to do a window check in your hook as well, although this controller will always be undefined during SSR

```
import {ParallaxContext} from 'react-scroll-parallax' 
const context = React.useContext(ParallaxContext)

if (context && context.parallaxController) {
...
} 
```

**Comment by AndrisBorbas** [comment]
> ```
> import {ParallaxContext} from 'react-scroll-parallax' 
> const context = React.useContext(ParallaxContext)
> 
> if (context) {
> ...
> } 
> ```

Could you explain where would you put this piece of code?

**Comment by ajsmth** [comment]
> > ```
> > import {ParallaxContext} from 'react-scroll-parallax' 
> > const context = React.useContext(ParallaxContext)
> > 
> > if (context) {
> > ...
> > } 
> > ```
> 
> Could you explain where would you put this piece of code?

in your consumer components - for example 
```
function MyComponent() {
const context = React.useContext(ParallaxContext)


React.useEffect(() => {
if (context) {
...
} 
}, [context])

}
```

**Comment by pveen2** [comment]
> > @Kevinnko @OPerel Out of curiosity I tried troubleshooting this issue again in a new Gatsby starter and I've been unable to reproduce it. Which is weird because I did see this issue in @OPerel's repo before.
> > Notably I'm using the latest Gatsby starter and applying the `ParallaxProvider` via the Gatsby `wrapPageElement` api.
> > You can see how I've integrated the parallax here. [Pull the repo](https://github.com/jscottsmith/gatsby-parallax-test) and scroll/navigate between pages -- should maintain consistent parallax.
> > [jscottsmith/gatsby-parallax-test@8fb8ef8](https://github.com/jscottsmith/gatsby-parallax-test/commit/8fb8ef8cdadda619275672d9ba9f0439dd77f0e2)
> > @Kevinnko are you using the `wrapPageElement` api? Can I take a look at your repo?
> 
> Hi @jscottsmith
> 
> I noticed that the issue happens when the pages you navigate between are different heights. For example, set index to `300vh` and page 2 to `100vh` - now when you navigate from index to page 2 the parallax on it will break.
> 
> I have tried using `useEffect` to call `parallaxController.update()` but that doesn't fix it.
> 
> Another strange thing is if you start on index and navigate to page 2, the parallax on page 2 will break, but will still be okay when you navigate back to index using a link. However, if you start on 2 page and navigate to index, the parallax there will not be broken even though it wasn't your entry page. But even in this case, going to page 2 will break the parallax there again.
> 
> I also suspected that it might be due to Gatsby "pre-rendering" pages of links when they are in view, but that doesn't seem to be the cause of the problem either because programmatically going to page 2 using `navigate('/page-2/')` does not make a difference from using `<Link>`.
> 
> You've also mentioned using a `setTimeout` and then calling `parallaxController.update()` but I found that even using this method, the update will only actually happen on the first scroll event and not when you call `update`. This seems to work fairly reliably so far though:
> 
> ```
> useEffect(() => {
>     window.requestAnimationFrame(() => {
>         parallaxController.update()
>     })
> })
> ```
> 
> Hope this helps.

@ajsmth  Can you maybe let me know where you put the useEffect?

**Comment by lucasmedeiros** [comment]
@fncombo your solution worked for me, thanks! :heart:

**Comment by qubis741** [comment]
@pveen2  something like this:
`const ParallaxCache = () => {
    const context = React.useContext(ParallaxContext)
    if (context) {
        const { parallaxController } = useController()

        useLayoutEffect(() => {
            const handler = () => parallaxController.update()
            window.addEventListener('load', handler)
            return () => window.removeEventListener('load', handler)
        }, [parallaxController])
    }
    return null
}`

**Comment by Sarah86** [comment]
Hey guys!
This worked for me:

    const context = React.useContext(ParallaxContext)
        
    useEffect(() => {
        if (context) {
            const { parallaxController } = useController();

            window.requestAnimationFrame(() => {
                parallaxController.update()
            })
        } 
    },[context])

**Comment by Sarah86** [comment]
Hey guys, what worked for me:

`const ParallaxImage = ({imgName}) => {
    const context = React.useContext(ParallaxContext)

    const handleOnLoad = () => {
        if (context) {
        const { parallaxController } = useController()
        parallaxController.update()
        }
        return null
    }

    return(
    <Parallax 
        y={[-50, 50]} 
        tagOuter="div" 
        styleInner={{height: '100vh'}} 
        styleOuter={{height: '100vh'}}>
        <Image 
            imgName={imgName} 
             onLoad={handleOnLoad}
            />
    </Parallax>
)};

export default withController(ParallaxImage); `


When I loaded the function using useEffect, it compiled but a white screen came out 1 second after the page has been showed.

My gatsby-browser.js is blank and I put the ParallaxProvider wrapping all the elements directly in the index... but I think this is not the problem, is just the way I am doing right now.

**Comment by LukasV** [comment]
Am I wrong in thinking that you cannot use React hooks conditionally? "Don’t call Hooks inside loops, conditions, or nested functions." - https://reactjs.org/docs/hooks-rules.html

The only work around which seems to be working for me at the minute is commenting out the thrown error in node_modules/react-scroll-parallax/cjs/components/useController.js. In this case my build goes through just fine and everything still works on front-end. 

if (!parallaxController) {
     return false;
    /*throw new Error(
      "Could not find `react-scroll-parallax` context value. Please ensure the component is wrapped in a <ParallaxProvider>"
    )*/
  }

**Comment by jscottsmith** [comment]
There was a bug that I discovered recently when refactoring this to a new version #123. I just published a patch that should fix these hacky `setTimeout` or `requestAnimationFrame`  solutions when calling `parallaxController.update()`.

Try the patch here `react-scroll-parallax@2.4.1` and LMK if anyone still encounters issues.
